### ISSUE TITLE
Warnings when compiling janapada dictionary

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-telugu#1]
I get the following warnings when producing dictionaries from the babylon file. It would be good to eliminate this (reason: warnings can drown out serious problems in the dictionary).

`processing janapada/janapada4.babylon

*\* (process:22242): WARNING **: Same word: అచట.

*\* (process:22242): WARNING **: Same word: achchanagaayalu.

*\* (process:22242): WARNING **: Same word: అరవుడు.

*\* (process:22242): WARNING **: Same word: ఆబ్కారి.

*\* (process:22242): WARNING **: Same word: ఆరుచు.

*\* (process:22242): WARNING **: Same word: ఎచ్చోటు.

*\* (process:22242): WARNING **: Same word: ఏకరా.

*\* (process:22242): WARNING **: Same word: ఒడ్డగిల్లు.

*\* (process:22242): WARNING **: Same word: ?E0.

*\* (process:22242): WARNING **: Same word: కలియు.

*\* (process:22242): WARNING **: Same word: kolaaramu.

*\* (process:22242): WARNING **: Same word: kolaaru.

*\* (process:22242): WARNING **: Warning 17651 : unknown tag: .

*\* (process:22242): WARNING **: Warning 17726 : unknown tag: isc  .

*\* (process:22242): WARNING **: Same word: క్వణము.

*\* (process:22242): WARNING **: Same word: చిట్టుముట్టాడు.

*\* (process:22242): WARNING **: Same word: చిమటా.

*\* (process:22242): WARNING **: Same word: चेयि.

*\* (process:22242): WARNING **: Same word: చకచక.

*\* (process:22242): WARNING **: Same word: చనువు.

*\* (process:22242): WARNING **: Same word: చర్రున.

*\* (process:22242): WARNING **: Same word: చులక.

*\* (process:22242): WARNING **: Same word: చొక్కాటము.

*\* (process:22242): WARNING **: Same word: చొల్లు.

*\* (process:22242): WARNING **: Same word: జగ.

*\* (process:22242): WARNING **: Same word: జడ.

*\* (process:22242): WARNING **: Same word: జవబియ్యము.

*\* (process:22242): WARNING **: Same word: జవాబు.

*\* (process:22242): WARNING **: Same word: జాగారము.

*\* (process:22242): WARNING **: Same word: జాగిలము.

*\* (process:22242): WARNING **: Same word: జాణ.

*\* (process:22242): WARNING **: Same word: జాను.

*\* (process:22242): WARNING **: Same word: జానుగు.

*\* (process:22242): WARNING **: Same word: జాప్యము.

*\* (process:22242): WARNING **: Same word: జిల్లా.

*\* (process:22242): WARNING **: Same word: జానకితాడు.

*\* (process:22242): WARNING **: Same word: జోక్యము.

*\* (process:22242): WARNING **: Same word: jamudaaDi.

*\* (process:22242): WARNING **: Same word: jamujaali.

*\* (process:22242): WARNING **: Same word: జాగిలాయి.

*\* (process:22242): WARNING **: Same word: జాప్యము.

*\* (process:22242): WARNING **: Same word: జామ.

*\* (process:22242): WARNING **: Same word: జామారు.

*\* (process:22242): WARNING **: Same word: జావళి.

*\* (process:22242): WARNING **: Same word: జూటు.

*\* (process:22242): WARNING **: Same word: టూకీ.

*\* (process:22242): WARNING **: Same word: తురుపు.

*\* (process:22242): WARNING **: Same word: తువర.

*\* (process:22242): WARNING **: Same word: దగ్గర.

*\* (process:22242): WARNING **: Same word: దరుజు.

*\* (process:22242): WARNING **: Same word: దాకొను.

*\* (process:22242): WARNING **: Same word: daagilimuchchulu.

*\* (process:22242): WARNING **: Same word: దుండుకము.

*\* (process:22242): WARNING **: Same word: ధూపము.

*\* (process:22242): WARNING **: Same word: నంజుకొను.

*\* (process:22242): WARNING **: Same word: నరియు.

*\* (process:22242): WARNING **: Same word: నిబద్ధి.

*\* (process:22242): WARNING **: Same word: निबद्धि.

*\* (process:22242): WARNING **: Same word: nibaddhi.

*\* (process:22242): WARNING **: Same word: నెపము.

*\* (process:22242): WARNING **: Same word: నేవము.

*\* (process:22242): WARNING **: Same word: పచరణ.

*\* (process:22242): WARNING **: Same word: పచరించు.

*\* (process:22242): WARNING **: Same word: पचरिंचु.

*\* (process:22242): WARNING **: Same word: pachariMchu.

*\* (process:22242): WARNING **: Same word: pacharinchu.

*\* (process:22242): WARNING **: Same word: పచారము.

*\* (process:22242): WARNING **: Same word: pachaaru.

*\* (process:22242): WARNING **: Same word: parivRdhuDu.

*\* (process:22242): WARNING **: Same word: parihaasamu.

*\* (process:22242): WARNING **: Same word: పాణిపడము.

*\* (process:22242): WARNING **: Same word: పృషదంశకము.

*\* (process:22242): WARNING **: Same word: पेरोजमु.

*\* (process:22242): WARNING **: Same word: pElaalu.

*\* (process:22242): WARNING **: Same word: pElalu.

*\* (process:22242): WARNING **: Same word: पोकालु.

*\* (process:22242): WARNING **: Same word: poTamarillu.

*\* (process:22242): WARNING **: Same word: బంజరు.

*\* (process:22242): WARNING **: Same word: మక్కి.

*\* (process:22242): WARNING **: Same word: maDati.

*\* (process:22242): WARNING **: Same word: manniyaDu.

*\* (process:22242): WARNING **: Same word: మరచిపోవు.

*\* (process:22242): WARNING **: Same word: ముతుక.

*\* (process:22242): WARNING **: Same word: మొయిలు.

*\* (process:22242): WARNING **: Warning 46712 : unknown tag: /b   rāṭsa-pani<br.

*\* (process:22242): WARNING **: Warning 47597 : unknown tag: i  .

*\* (process:22242): WARNING **: Same word: లికుచము.

*\* (process:22242): WARNING **: Same word: lEkapOtE.

*\* (process:22242): WARNING **: Same word: వంజరము.

*\* (process:22242): WARNING **: Same word: vaDlavaaDu.

*\* (process:22242): WARNING **: Same word: వణకు.

*\* (process:22242): WARNING **: Same word: valuda.

*\* (process:22242): WARNING **: Same word: వల్మికము.

*\* (process:22242): WARNING **: Same word: వాళి.

*\* (process:22242): WARNING **: Same word: విటతాటము.

*\* (process:22242): WARNING **: Same word: viDiyamu.viDemu.

*\* (process:22242): WARNING **: Same word: వెలపల.

*\* (process:22242): WARNING **: Same word: veluvaDu.

*\* (process:22242): WARNING **: Same word: vEgi.

*\* (process:22242): WARNING **: Same word: వేపి.

*\* (process:22242): WARNING **: Same word: వేయి.

*\* (process:22242): WARNING **: Same word: वेयि.

*\* (process:22242): WARNING **: Same word: vEyi.

*\* (process:22242): WARNING **: Same word: శాడ్వలము.

*\* (process:22242): WARNING **: Same word: shmashaanamu.

*\* (process:22242): WARNING **: Same word: సంతోసము.

*\* (process:22242): WARNING **: Same word: sannuti.

*\* (process:22242): WARNING **: Same word: సాజము.

*\* (process:22242): WARNING **: Warning 55322 : unknown tag: .

*\* (process:22242): WARNING **: Same word: సూరాకారము.

*\* (process:22242): WARNING **: Same word: सेबासु.

*\* (process:22242): WARNING **: Same word: hajaaramu.

*\* (process:22242): WARNING **: Same word: hajuru.

*\* (process:22242): WARNING **: Same word: hurumaMji.

*\* (process:22242): WARNING **: Same word: hurumuMji.

*\* (process:22242): WARNING **: Same word: hurumanji.

*\* (process:22242): WARNING **: Same word: hurumunji.

*\* (process:22242): WARNING **: Same word: కుస్తీ.

*\* (process:22242): WARNING *_: Same word: జనానా.
*_ Message: Over.
*\* Message: wordcount: 19610.
*\* Message: synwordcount: 49130.
`

**Comment by damooo** [comment]
Ha. I also got those. Reason is dictionary it self have duplicate words in
synonyms for some 100 words. So it is not programmebly accessible. If I
remove them with brute force, it well remove all remaining 19000 word
synonyms. so some manual dictionary correction have to be done, and that
should not effect our words, synonyms database and fine relation between
their position now we have. so I will do it gradually, and remove them, in
updates soon if required.

And regarding those sites zim files, thanks for that list of websites. I am
also thinking about zimming Sanskritdocuments website, and you said it : ),
I will do very soon.
12 మార్చి, 2016 5:24 [AM]న, "Vishvas Vasuki" <notifications@github.com>
వ్రాసినది:

**Comment by vvasuki** [comment]
नमस्ते दामोदर,

I see lines like: కొలారము|కొలారు|కొలారుబండి|కొల్లారుబండి|कोलारमु|कोलारु|कोलारुबंडि|kolaaramu|kolaaru|kolaarubaMDi|kolaaramu|kolaaru|kolaarubanDi . Observe how kolaaramu appears twice. It should not. If you ensure that the headword list is unique, many of the warnings will go away. I don't know what scripting language you're using, but one way to do it is to put the headwords in a "set" data-structure before printing them out by joining with |. 

This will not affect the synonyms in any way.

**Comment by damooo** [comment]
ॐ । All duplicates suppressed, and updated , A new catalyst file also added.

**Comment by vvasuki** [comment]
Confirmed, thanks!
