### ISSUE TITLE
Reduce the HTML markup in pAribhAShika nighaNTu

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-telugu#13]
Of course, I agree that hyperlinks, page numbers etc.. should be retained, but about the rest: I wonder if so much HTML/ CSS markup is really more helpful than harmful (memory requirement for colordict users who cannot use dict.dz files directly without uncompressing - people have complained to me in the past about this, and have been reluctant to install dicts as a result). 

`<style>div.vyvhr_tera{font-family:Verdana, "Lucida Sans Unicode", sans-serif;margin: 0em;line-height:1.5em;}div.vyvhr_shirshika{max-width:20em;height:3em;float:left;text-align:left;}div.vyvhr_patra{background: #ccc193;border-radius:5px;margin:0 auto 0 auto;padding: 1em;max-width:55.8em;color:#1b1205;font-size: 1em;}div.vyvhr_pnum{max-width:10em;height:3em;float:right;text-align:right;}div.vyvhr_pada{border:1px solid black;min-width:7em;padding:0.3em;}div.vyvhr_floatclr{clear:left;}a.vyvhr_a_pada:link,a.vyvhr_a_pada:visited,a.vyvhr_pada,a.vyvhr_pglink{color: #1b1205; text-decoration: none;}a.vyvhr_a_pada:hover{text-decoration: underline;color:#9b0606;}a.vyvhr_pglink:hover{text-decoration: underline;}span.vyvhr_span_bsbg{color: brown;}div.vyvhr_vivaraNa{padding-top:0.1em;}div.vyvhr_bsbg{margin-bottom:1.0em;}div.vyvhr_nanartha::before{content:"• ";}</style><div class="vyvhr_tera"><div class="vyvhr_patra"><div class="vyvhr_shirshika"><div class="vyvhr_pada"><B>abscission</B></div></div><div class="vyvhr_pnum"><a class="vyvhr_pglink" href="_vyvhr_pn3">↶</a><a class="vyvhr_pglink" href="_vyvhr_pn4">p4</a><a class="vyvhr_pglink" href="_vyvhr_pn5">↷</a><br><a class="vyvhr_pglink" href="_vyvhr@115">«</a><span class="vyvhr_wnum">పదం 20</span><a class="vyvhr_pglink" href="_vyvhr@117">»</a></div><div class="vyvhr_floatclr" style="clear:left;"><hr class="vyvhr_titlesepr"></div><div class="vyvhr_bsbg"><div class="vyvhr_vivaraNa"><div class="vyvhr_nanartha"><span class="padartha">(పుండు) <a class="vyvhr_a_pada" href="కోత">కోత</a></span>, <span class="padartha"><a class="vyvhr_a_pada" href="కర్తనం">కర్తనం</a></span>; </div></div></div></div></div></div>
`

**Comment by damooo** [comment]
Yes, I too concerned abot it. But those all tags are not actually for display.. but for grouping. This perticular dict contains a nice format , and to make that all accessible for any other application i grouped them as in dictionary.major work is for that, and used tags for them. If any web interface built in future we can just choose exact desired nodes, and groups , from all explanation. i.e. for machine accessability ... . and words with big explanations and words are reasonable in size.  all And major part of above thing is css inserted between <style> and </style> tags. which can be external css file, and it reduces everything completely. but only desktop golden dict suppotes external css, and hence have to be added for every word. It seems compiled dicts are very small , hense i bypassed my that concern.

**Comment by damooo** [comment]
Or i can add  another minimised edition too., and keep previous file part of resources folder.

**Comment by vvasuki** [comment]
> Or i can add another minimised edition too., and keep previous file part of resources folder.

I think that this is an excellent idea!

**Comment by damooo** [comment]
updated. and page navigation removed as words are independant and non historical.

**Comment by vvasuki** [comment]
This is how a pAribhAShika nighaNTu entry for kaTi looks on my phone goldendict - 
![image](https://cloud.githubusercontent.com/assets/2664797/24386314/cb053210-1323-11e7-8aa6-318ee11eebf5.png) .

The colordict does not even show the entry.

(This is reminiscent of https://github.com/sanskrit-coders/stardict-sanskrit/issues/23 ). I am not sure if this is the latest version of teh nighaNTu after your last update last month, but can check.

**Comment by damooo** [comment]
that is old version, i removed it, and added clean version already.

**Comment by vvasuki** [comment]
Confirmed - thanks!
