### ISSUE TITLE
Add varga-panchama-forms devanAgarI.

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-telugu#4]
Currently we have: అంకె|अंके|aMke|anke|अंकॆ

We should have: అంకె|अंके|aMke|anke|अंकॆ|अङ्के|अङ्कॆ

This facilitates cross-dictionary-links. Sanskrit dictionaries use the varga panchama forms.

**Comment by damooo** [comment]
ॐ । 
added, and updated. example 
పాంచజన్యము|पांचजन्यमु|paaMchajanyamu|paanchajanyamu|पाञ्चजन्यमु
అంకె|अंके|aMke|anke|अंकॆ|अङ्के|अङ्कॆ
అంట్రింత|अंट्रिंत|aMTriMta|anTrinta|अण्ट्रिन्त
 and so on. added catalysts VGN and VGT to grep and do any thing with them in catayst file.

**Comment by vvasuki** [comment]
Confirmed, thanks!
