### ISSUE TITLE
Include the original headword in the meaning line

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-telugu#7]
For various reasons (Eg, the one  noted in [this comment](https://github.com/sanskrit-coders/stardict-telugu/issues/5#issuecomment-196543800) ), it is desirable to include the original headword in the meaning line.

For example:

```
"అ<br>—————————————————————————<br>దేవనాగరి : अ <br>ఉచ్ఛారణ : a,a<br>—————————————————————————<br><br>[Drav.]<br><br>The base of the demonstrative pronoun  అతడు, వాడు, అది."<br><br>
"
```

**Comment by damooo** [comment]
added vishvas ji. now it contains main head word

**Comment by vvasuki** [comment]
You've not pushed the change yet, I think. Don't see it..

**Comment by damooo** [comment]
తెలుగు పదం : అంకవిద్య<br>దేవనాగరి  , before devanagari word, with heading 'తెలుగు పదం :'  in eveery word description.

**Comment by vvasuki** [comment]
ok thanx
