### ISSUE TITLE
Merging both telugu dictionaries for good.

### ISSUE THREAD

**Issue by damooo** [indic-dict/stardict-telugu#8]
As wiktionary is rewritten by reffering so many standard telugu dicts, It will be good if janapada, and wiktionary get merged into single one , with linking both also with synonym head  words of them .  then it will work as even english to telugu, and telugu to english, and also telugu to telugu comprehensive dictionay (for now they are only tel-eng , and tel-tel individually). as wiktionary contains remaining language translations , in translations heading of every word, it will be more effective if those all translations too added to head word... then it will work too nicely with two sets of words cooperating each other for synonyms,, translations,transliterations, and being one single comprehensive dictionary.

**Comment by damooo** [comment]
merged, and all translations too added to head word. and devanagari transliterations added in head words, and descriptions for wiktionary part. inter linking done. source file splitted into two , as size limit exceeded, but compiled dictionaries are only 15MB.

**Comment by vvasuki** [comment]
Dear dAmodara.

I don't think that merging dictionaries in this way is a good idea because:
- Users would like to be clear about the source of an entry - is it from jAnapada? Is it from wiktionary? One may value the former over the latter. If you merge everything, it this is tougher.
- There is no point in merging dictionaries because:
  - the size restrictions you mention, and the resulting ugly file structure.
  - dictionary apps will show definitions from all dictionaries any way.
  - just the fact that wiktionary has (other-language) synonyms would suffice for the dictionary app to pull up those definitions and show them as well.

In fact, if at all possible it might be good to segregate en-tel from te-en in wiktionary.

Given this, how about undoing this merge?

**Comment by damooo** [comment]
hmm ,, yes ..but, Wiktionary online itself not one single dictionary, but we added everything  from some 8 standard dictionaries of our  language,  and janapada also going to be added soon. It is intended to be one single comprehensive reference , and janapada is  medium in size , and contain only some 20000 valuble words,where  as wiktionary  is super large. And when  seperated  they are giving results in  order of dictionaries ,i.e first from dict1,  and then from dict2. where as after merging all those synonymical results are sorted by content or words. so same words from both dicts  are adjecent,  and so easy  to refer both both eng, and  tel examples, descripions at look efficiently. otherwise they are randomly sorted by dicts seperation.  if we search for word 'end' , then some 25 long  results page coming. if it is  not well ordered it is not ideal to scroll in  page to find same word in differant dicts .this is main reason i did this for,  and some wanted one single dict, instead of multiple.

But as u said for  any who want only from janapada, they may find it difficult, as it has  authorship identity,  where as wiktionary doesn't have seperate identity, but mix of all main dicts well organised into headings. So i too think janapada  should be in seperated form. 

so i will add janapada too seperately. So that they can choose that one only.
and wiktionary  too to seperate folder,
and this present combined dictionary in another folder but with only dictionary files, without source, as we can get source from appending previous two.

 then it will be good enough i think. As we can choose any of the way. and file structure also nice, as there is no source in combined folder

**Comment by vvasuki** [comment]
Sounds good, thanks!

Btw, regarding " And when seperated they are giving results in order of dictionaries ,i.e first from dict1, and then from dict2." - this sort order is configurable in GoldenDict.

**Comment by damooo** [comment]
Oh, good then. And I will push them today itself, with some minor corrections in content : )

**Comment by damooo** [comment]
done.

**Comment by vvasuki** [comment]
Thanks!
